import requests
import pandas as pd
import time
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# --- CONFIGURATION ---
# AUTH URL: https://www.strava.com/oauth/authorize?client_id=YOUR_ID&response_type=code&redirect_uri=http://localhost/exchange_token&approval_prompt=force&scope=activity:read_all
# Copy your 'Access Token' from https://www.strava.com/settings/api or use the one generated by your previous script
ACCESS_TOKEN = os.getenv("ACCESS_TOKEN")

def get_strava_activities(token):
    url = "https://www.strava.com/api/v3/athlete/activities"
    headers = {'Authorization': f"Bearer {token}"}
    
    activities = []
    page = 1
    per_page = 200 # Maximum allowed per page
    
    print("Downloading data from Strava...")
    
    while True:
        params = {'per_page': per_page, 'page': page}
        response = requests.get(url, headers=headers, params=params)
        
        if response.status_code != 200:
            print(f"Error: {response.status_code}")
            break
            
        data = response.json()
        
        if not data:
            break # No more activities found
            
        activities.extend(data)
        print(f"Page {page} processed ({len(data)} activities)")
        page += 1
        
    return pd.DataFrame(activities)

# EXECUTION
df = get_strava_activities(ACCESS_TOKEN)


if not df.empty:
    # Create data directory if it doesn't exist
    if not os.path.exists('data'):
        os.makedirs('data')

    # RUNNING ACTIVITIES
    # 1. Filter only 'Run' activities
    df_run = df[df['type'] == 'Run'].copy()
    
    # 2. Convert dates to datetime objects
    df_run['start_date_local'] = pd.to_datetime(df_run['start_date_local'])
    
    # 3. Select columns of interest for training analysis
    columns_of_interest = [
        'name', 'start_date_local', 'distance', 'moving_time', 
        'elapsed_time', 'total_elevation_gain', 'average_speed', 
        'max_speed', 'average_heartrate', 'max_heartrate','pr_count'
    ]
    
    # Ensure columns exist (heartrate might be null if no sensor was used)
    existing_cols = [c for c in columns_of_interest if c in df_run.columns]
    final_df_run = df_run[existing_cols].copy()
    
    # 4. Useful Conversions
    # Distance to Kilometers
    final_df_run['distance_km'] = final_df_run['distance'] / 1000
    
    # Average Pace (min/km) calculation
    # Formula: (1 / speed in m/s) * 1000 / 60  => 16.6667 / speed
    final_df_run['pace_min_km'] = 16.6667 / final_df_run['average_speed'] 

    print(f"Done! {len(final_df_run)} runs extracted.")
    print(final_df_run.head())
    
    # Save to CSV for sharing or later analysis
    final_df_run.to_csv('data/run.csv', index=False)
    

    # SWIMING ACTIVITIES
    # 1. Filter only 'SWIM' activities
    df_swim = df[df['type'] == 'Swim'].copy()
    
    # 2. Convert dates to datetime objects
    df_swim['start_date_local'] = pd.to_datetime(df_swim['start_date_local'])
    
    # Ensure columns exist (heartrate might be null if no sensor was used)
    existing_cols = [c for c in columns_of_interest if c in df_swim.columns]
    final_df_swim = df_swim[existing_cols].copy()
    
    # 4. Useful Conversions
    
    # Average Pace (min/km) calculation
    # Formula: (1 / speed in m/s) * 1000 / 60  => 16.6667 / speed
    final_df_swim['pace_seconds_100m'] = 100 / final_df_swim['average_speed']
   
    print(f"Done! {len(final_df_swim)} swim activities extracted.")
    print(final_df_swim.head())
    
    # Save to CSV for sharing or later analysis
    final_df_swim.to_csv('data/swim.csv', index=False)


     # BIKE ACTIVITIES
    # 1. Filter only 'BIKE' activities
    df_bike = df[df['type'] == 'Ride'].copy()
    
    # 2. Convert dates to datetime objects
    df_bike['start_date_local'] = pd.to_datetime(df_bike['start_date_local'])
    
    # Ensure columns exist (heartrate might be null if no sensor was used)
    existing_cols = [c for c in columns_of_interest if c in df_bike.columns]
    final_df_bike = df_bike[existing_cols].copy()
    
    # 4. Useful Conversions
    
    # Average Pace (min/km) calculation
    # Formula: (1 / speed in m/s) * 1000 / 60  => 16.6667 / speed
    final_df_bike['pace_seconds_100m'] = 100 / final_df_bike['average_speed']
   
    print(f"Done! {len(final_df_bike)} swim activities extracted.")
    print(final_df_bike.head())
    
    # Save to CSV for sharing or later analysis
    final_df_bike.to_csv('data/bike.csv', index=False)
    

else:
    print("No data found or the token has expired.")